const C=[["Албания","Тирана","AL"],["Андорра","Андорра-ла-Велья","AD"],["Армения","Ереван","AM"],["Австрия","Вена","AT"],["Азербайджан","Баку","AZ"],["Беларусь","Минск","BY"],["Бельгия","Брюссель","BE"],["Болгария","София","BG"],["Босния и Герцеговина","Сараево","BA"],["Ватикан","Ватикан","VA"],["Великобритания","Лондон","GB"],["Венгрия","Будапешт","HU"],["Германия","Берлин","DE"],["Греция","Афины","GR"],["Грузия","Тбилиси","GE"],["Дания","Копенгаген","DK"],["Ирландия","Дублин","IE"],["Исландия","Рейкьявик","IS"],["Испания","Мадрид","ES"],["Италия","Рим","IT"],["Казахстан","Астана","KZ"],["Кипр","Никосия","CY"],["Латвия","Рига","LV"],["Литва","Вильнюс","LT"],["Лихтенштейн","Вадуц","LI"],["Люксембург","Люксембург","LU"],["Мальта","Валлетта","MT"],["Молдова","Кишинёв","MD"],["Монако","Монако","MC"],["Нидерланды","Амстердам","NL"],["Норвегия","Осло","NO"],["Польша","Варшава","PL"],["Португалия","Лиссабон","PT"],["Россия","Москва","RU"],["Румыния","Бухарест","RO"],["Сан-Марино","Сан-Марино","SM"],["Северная Македония","Скопье","MK"],["Сербия","Белград","RS"],["Словакия","Братислава","SK"],["Словения","Любляна","SI"],["Турция","Анкара","TR"],["Украина","Киев","UA"],["Финляндия","Хельсинки","FI"],["Франция","Париж","FR"],["Хорватия","Загреб","HR"],["Черногория","Подгорица","ME"],["Чехия","Прага","CZ"],["Швейцария","Берн","CH"],["Швеция","Стокгольм","SE"],["Эстония","Таллин","EE"]];
const major=new Set(["DE","FR","IT","ES","GB","PL","UA","RU","NL","BE","AT","CH","SE","NO","DK","FI","GR","PT","CZ","IE","RO","HU","BG","TR"]);const hard=new Set(C.map(x=>x[2]).filter(x=>!major.has(x[0])));let pool=[],i=0,cur,score=0,streak=0,done=false,mapData;
const $=x=>document.getElementById(x);$("start").onclick=start;$("restart").onclick=start;$("next").onclick=()=>{i++;render()};
function sh(a){return a.slice().sort(()=>Math.random()-.5)}
function start(){let d=$("difficulty").value;pool=sh(C.filter(x=>d==="all"||(d==="standard"?major:hard).has(x[2])));let n=$("count").value==="all"?pool.length:+$("count").value;pool=pool.slice(0,n);i=0;score=0;streak=0;$("score").textContent=0;$("quiz").classList.remove("hidden");render()}
function render(){if(i>=pool.length)return finish();done=false;cur=pool[i];$("progress").textContent=(i+1)+" / "+pool.length;$("streak").textContent="Серия: "+streak+" 🔥";$("feedback").textContent="";$("next").classList.add("hidden");$("mapPanel").classList.add("hidden");$("answers").replaceChildren();let m=$("mode").value;if(m==="mixed")m=sh(["country-capital","capital-country","map-country","country-map","capital-map"])[0];if(m==="map-country"||m==="country-map"||m==="capital-map")return mapQuestion(m);let correct=m==="country-capital"?cur[1]:cur[0];$("question").innerHTML=m==="country-capital"?"Столица: <strong>"+cur[0]+"</strong>?":"Какая страна имеет столицу <strong>"+cur[1]+"</strong>?";let vals=sh([correct].concat(sh(C.map(x=>m==="country-capital"?x[1]:x[0]).filter(x=>x!==correct)).slice(0,3)));let box=document.createElement("div");box.className="answers";vals.forEach(v=>{let b=document.createElement("button");b.textContent=v;b.onclick=()=>answer(b,v===correct,correct);box.appendChild(b)});$("answers").appendChild(box)}
function answer(b,ok,correct){if(done)return;done=true;document.querySelectorAll(".answers button").forEach(x=>x.disabled=true);b.classList.add(ok?"correct":"wrong");$("feedback").textContent=ok?"✓ Правильно!":"✗ Ответ: "+correct;if(ok){score+=10+streak*2;streak++}else streak=0;$("score").textContent=score;$("next").classList.remove("hidden")}
async function mapQuestion(m){$("mapPanel").classList.remove("hidden");$("question").innerHTML=m==="map-country"?"Какая это страна? Нажми на неё.":"Найди на карте: <strong>"+(m==="country-map"?cur[0]:cur[1])+"</strong>";$("mapHint").textContent="Нажми на нужную страну.";await loadMap();document.querySelectorAll(".country").forEach(x=>x.classList.remove("target"));if(m!=="map-country"){let names=mapNames(cur[2]).map(norm);document.querySelectorAll(".country").forEach(x=>{if(names.includes(norm(x.dataset.name)))x.classList.add("target")})}}
async function loadMap(){if(mapData)return draw();try{let r=await fetch("https://raw.githubusercontent.com/leakyMirror/map-of-europe/master/GeoJSON/europe.geojson");mapData=await r.json();draw()}catch(e){$("map").innerHTML="<p>Карта не загрузилась. Проверь интернет.</p>"}}
function draw(){let s=document.createElementNS("http://www.w3.org/2000/svg","svg");s.setAttribute("viewBox","0 0 1000 700");s.setAttribute("preserveAspectRatio","xMidYMid meet");mapData.features.forEach(f=>{let name=f.properties.NAME||f.properties.name||f.properties.ADMIN||"";paths(f.geometry).forEach(d=>{let p=document.createElementNS("http://www.w3.org/2000/svg","path");p.setAttribute("d",d);p.classList.add("country");p.dataset.name=name;p.onclick=()=>mapAnswer(p,name);s.appendChild(p)})});$("map").replaceChildren(s)}
function paths(g){let cv=a=>a.map((q,k)=>(k?"L":"M")+((q[0]+180)/360*1000).toFixed(1)+" "+((90-q[1])/180*700).toFixed(1)).join(" ")+"Z",o=[];if(g.type==="Polygon")o.push(g.coordinates.map(cv).join(" "));if(g.type==="MultiPolygon")g.coordinates.forEach(x=>o.push(x.map(cv).join(" ")));return o}
function norm(x){return x.toLowerCase().replace(/[^a-zа-яё]/gi,"")}
function mapNames(code){let n={AL:["Albania"],AD:["Andorra"],AM:["Armenia"],AT:["Austria"],AZ:["Azerbaijan"],BY:["Belarus"],BE:["Belgium"],BG:["Bulgaria"],BA:["Bosnia and Herzegovina"],VA:["Vatican"],GB:["United Kingdom"],HU:["Hungary"],DE:["Germany"],GR:["Greece"],GE:["Georgia"],DK:["Denmark"],IE:["Ireland"],IS:["Iceland"],ES:["Spain"],IT:["Italy"],KZ:["Kazakhstan"],CY:["Cyprus"],LV:["Latvia"],LT:["Lithuania"],LI:["Liechtenstein"],LU:["Luxembourg"],MT:["Malta"],MD:["Moldova"],MC:["Monaco"],NL:["Netherlands"],NO:["Norway"],PL:["Poland"],PT:["Portugal"],RU:["Russia"],RO:["Romania"],SM:["San Marino"],MK:["North Macedonia"],RS:["Serbia"],SK:["Slovakia"],SI:["Slovenia"],TR:["Turkey"],UA:["Ukraine"],FI:["Finland"],FR:["France"],HR:["Croatia"],ME:["Montenegro"],CZ:["Czechia","Czech Republic"],CH:["Switzerland"],SE:["Sweden"],EE:["Estonia"]};return n[code]||[]}
function mapAnswer(p,name){if(done)return;let ok=mapNames(cur[2]).map(norm).includes(norm(name));done=true;p.classList.add(ok?"correct":"wrong");$("feedback").textContent=ok?"✓ Правильно — "+cur[0]+" · "+cur[1]:"✗ Это "+name+". Нужно: "+cur[0];if(ok){score+=10+streak*2;streak++}else streak=0;$("score").textContent=score;$("next").classList.remove("hidden")}
function finish(){$("question").innerHTML="Тест завершён 🎉";$("answers").replaceChildren();$("feedback").textContent="Результат: "+score+" очков из "+pool.length+" вопросов.";$("next").classList.add("hidden");$("mapPanel").classList.add("hidden")}